!****************************************************************************************************
! FVW_Types
!....................................................................................................
!*****************************************************************************************************
MODULE FVW_Types
! This module contains all of the user-defined types needed in FVW. It also contains copy, destroy, pack, and
! unpack routines associated with each defined data type. This code will be generated by the FAST Registry.
!----------------------------------------------------------------------------------------------------
  USE IfW_FFWind_Types
  USE IfW_HHWind_Types
  USE InflowWind_Types
  USE NWTC_Library
  USE Precision
  USE AeroDyn14_Types

  IMPLICIT NONE

! =========  FVW_turbine_blade  =======
  TYPE, PUBLIC :: FVW_ParameterType
  
      !From AeroDyn
      REAL(ReKi) :: DtAero      ! Time interval for aerodynamic calculations [-]
      INTEGER(IntKi)  :: NELM
      REAL(ReKi) , DIMENSION(:), ALLOCATABLE, SAVE  :: RELM
      INTEGER(IntKi)  :: NumBl      ! Number of Blades [-]
      REAL(ReKi)  :: Radius      ! Rotor radius [-]
      REAL(ReKi) , DIMENSION(:), ALLOCATABLE, SAVE  :: C ! Chord of each blade element from input file [-]
      REAL(ReKi)  :: HH
      REAL(ReKi)  :: HubRad
      REAL(ReKi)  :: Time
      TYPE(AD14_InputType) :: ADInput
      TYPE(AirfoilParms) :: AirfoilParm
      TYPE(Airfoil)      :: AirfoilOut
      REAL(ReKi) , DIMENSION(:), ALLOCATABLE, SAVE  :: CDD 
      REAL(ReKi) , DIMENSION(:), ALLOCATABLE, SAVE  :: CLL 
      REAL(ReKi) , DIMENSION(:), ALLOCATABLE, SAVE  :: CMM
      
      
      !From FAST
      REAL(ReKi) :: TMax
      
      !From ElastoDyn
      REAL(ReKi) :: RotSpeed
      
      !From InflowWind
      TYPE(IfW_ParameterType)  :: IfW_Params
      TYPE(IfW_OtherStateType)  :: IfW_OtherStates
      TYPE(IfW_InputType)  :: IfW_Inputs
      TYPE(IfW_OutputType)  :: IfW_Outputs
      TYPE(IfW_ContinuousStateType)  :: IfW_ContStates
      TYPE(IfW_DiscreteStateType)  :: IfW_DiscStates
      TYPE(IfW_ConstraintStateType)  :: IfW_ConstrStates
      TYPE(IfW_InitInputType)  :: IfW_InitInputs
      TYPE(IfW_InitOutputType)  :: IfW_InitOutput
      
  END TYPE

END MODULE FVW_Types
!ENDOFREGISTRYGENERATEDFILE
